# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35fe395e1c80a213fe72580f4ba610fe81830a16a0846b232789cdfc4602303b916836011891757c3f0c60884a665bbad1991e339a8a3f636ae762e5d966fd9e

test:
  secret_key_base: 5eac88e0c2e69121fa782d4536661535016b58c692333fefcb3aacd88b59bd14ada57fd04c28fcbf76fbbd4fc4207ca80240f7e422e6b183473dce56e1718dad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
